// Javascript helper functions for HTML gallery generated by shrinkImages.sh

function swap (e) {
    // Swaps between original and converted image by changing a parent class
    var but = e.currentTarget;
    var el = but.parentNode;
    if (el.className == "showOrig") {
        el.className = "showConv";
    } else {
        el.className = "showOrig";
    }
}

function togRes (e) {
    // Toggles between showing small and fullsize images
    var bdy = document.body;
    if (bdy.className == "small") {
        bdy.className = "";
    } else {
        bdy.className = "small";
    }
}

function nextPic (e) {
    // Move to the next image, if available
    var now = e.currentTarget.parentNode;
    var go  = now.nextElementSibling;
    if (go instanceof HTMLElement) {
        now.className = "hide";
        go.className = "show";
    }
}

function prevPic (e) {
    // Move to the previous image, if available
    var now = e.currentTarget.parentNode;
    var go  = now.previousElementSibling;
    if (go instanceof HTMLElement) {
        now.className = "hide";
        go.className = "show";
    }
}
